### ISSUE TITLE
Usage problems

### ISSUE THREAD

**Issue by JunKim-Worms** [eyalbenda/xQTLstats#1]
Dear Professor Eyal Ben David,

Hi, I'm Jun studying natural variations in several nematodes.
Thanks for your great work and contributions. Your xQTL paper was extremely elegant, so I'm trying to adjust your method to my lovely nematodes.

I'd be grateful if you answered following questions.

I have (1) a contig-level genome assembly for my nematode and (2) whole genome sequencing data of selected populations using your method.

I thoroughly read your paper, and used these scripts:
`bwa mem` for read alignment,
`samtools sort` for sorting BAM outputs,
`sambamba markdup` for removing PCR duplicates, and
`bam-readcount` for counting the number of reads for each allele.
In addition, I got variant sets of two parental lines.

Would you please let me know how I can transform these information to the suitable inputs for `xQTLstats`?
I also tried to use your `cexQTLview`, but the `dfAllFreqsProcessed.rds.gz` file looks like already fully processed and filtered. If you can share example scripts to produce this processed version, then I can probably follow it.

Second, is it possible to use `xQTLstats` for other animals, such as my nematode? I think you used Erik's N2xCB4856 RIAIL data as described in `getMeffectiveForCelegans.R`. If possible, I'd like to generate similar data for my nematode. Would you please share your scripts to produce this type of data?

Thank you so much!
Yours sincerely,
Jun.

**Comment by eyalbenda** [comment]
Hi Jun,

Of course, I'll be happy to help in getting our method to run. 

> 
> Would you please let me know how I can transform these information to the suitable inputs for xQTLstats?
> I also tried to use your cexQTLview, but the dfAllFreqsProcessed.rds.gz file looks like already fully processed and filtered. If you can share example scripts to produce this processed version, then I can probably follow it.

I'll be happy to help you there. I have code to parse the bam-readcount output to the data frames used by xQTLstats. I'll annotate it and upload a version to the repository to facilitate using the package.


> Second, is it possible to use xQTLstats for other animals, such as my nematode? I think you used Erik's N2xCB4856 RIAIL data as described in getMeffectiveForCelegans.R. If possible, I'd like to generate similar data for my nematode. Would you please share your scripts to produce this type of data?

The strength of xQTLstats in comparison to other tools is that it takes advantage of recombination rates to boost the power and resolution of QTL mapping. This is particularly relevant in nematodes where recombination rates are highly skewed. The problem is that you need a recombination map to take advantage of it, and that's what the _geneticMap_ argument expects. You can test running the mapping without a genetic map by just creating a uniform vector (1:number of snps). This could work, although I haven't tested it.

If you're doing the xQTL without a genetic map, there are two other programs you can also try, MULTIPOOL and QTLseqR. They may or may not be easier to run, I've no experience with them. I'll be happy to help you run xQTLstats, of course, but the main advantage over the other software is when you have a genetic map.
https://jueseph.github.io/Tutorial-BSA-Python/yeast_bulk_segregant_analysis_example.html
https://github.com/bmansfeld/QTLseqr

**Comment by JunKim-Worms** [comment]
Dear Professor Eyal Ben David,

Thank you so much for your kink reply. I will be waiting for your code!

Thanks again!
Yours sincerely,
Jun.

**Comment by eyalbenda** [comment]
Hi Jun,

I'll add a minimal working example to the code over the weekend. In the meantime, the following can be used to parse the counts for the reference allele given a bam readcount output file (fread is part of the data table package):
```

referenceParse = function(bamCountFile,freqs=F)
{
  bamCountFile = as.matrix(bamCountFile)
  orderNucs = c("a"=1,"c"=2,"g"=3,"t"=4)
  countVec = NULL
  intCols = apply(bamCountFile,1,function(x)x[5:8][orderNucs[tolower(x[3])]])
  
  countVec = as.numeric(sapply(strsplit(intCols,":"),function(x)x[2]))
  
  if(freqs)
    countVec = countVec/as.numeric(bamCountFile[,4])
  countVec
}
coverageParse = function(bamCountFile)
{
  bamCountFile = as.matrix(bamCountFile)
  as.numeric(bamCountFile[,4])
}

readcount_file = "path_to_file"
readcount = data.frame(fread(sprintf("cut -f1,2,3,4,6,7,8,9 %s",readcount_file)))

counts_ref = referenceParse(readcount)
coverage = coverageParse(readcount)
counts_alt = coverageParse - referenceParse
```

You can use this code to get the reference and alternative allele counts for each bam-readcount output file. Note that this code takes all the coverage that isn't reference to be the alt allele. In our paper, we generated a CB4856 reference, and had bam readcount results for that as well, so we could use that directly. However, I tested it, and it made no difference compared to just subtracting the N2 counts from the total coverage.

**Comment by JunKim-Worms** [comment]
Dear Professor Eyal Ben David,

Thank you so much! I really appreciate your kind efforts.

Your code worked very well. I changed the last line:
from `counts_alt = coverageParse - referenceParse`
to `counts_alt = coverage - counts_ref`

It produced a single vector, and its size was similar, but ~3% smaller than genome size.

I will be waiting for your working example.

Many thanks!

Yours sincerely,
Jun.

**Comment by eyalbenda** [comment]
Hi Jun,

The reason why you're getting a smaller sized vector is that bam-readcount doesn't emit sites with no coverage. For this reason, I usually use the bed file as template and "merge" the bam-readcount output into it.
I wanted to draw your attention to a new resource I've made available which will hopefully make it easier to work with xQTLstats. I made vignette for reproducing the Abamectin resistance mapping we did in the paper. I'm currently uploading the updated version which includes the resources to reproduce the analysis to github.
In the meantime, you can find the Vignette here:

https://rpubs.com/eyalbd/738820

**Comment by JunKim-Worms** [comment]
Dear Professor Eyal Ben David,

I really, truly appreciate your kind helps! I'm thoroughly reading your vignette, and maybe I can analyze my data.
I will cite your paper, this github and the vignette in my paper. If you have any requests, please let me know.

May I ask you one more question? Would you please let me know if there is any specific process for constructing a genetic map?

I'm currently generating other sequencing data to construct a genetic map for my species, and will use it as an input of your xQTLstats. I found several ways to construct a genetic map, but I'd like to follow your method if xQTLstats requires a specific type of inputs.

Thank you so much again!
Yours sincerely,
Jun.

**Comment by eyalbenda** [comment]
Dear Jun,

There are several software packages for computing a genetic map. It really
depends on the study design you're working with and what data you expect to
have in the end.
A classic resource in this field is Karl Broman's r/qtl tutorial:
https://rqtl.org/tutorials/geneticmaps.pdf
I suggest you look there as a first place to start. If you use it to
calculate a genetic map, you will have a r/qtl cross object, which you can
process into a genome object (for xQTLstats) easily by following what I did
for N2xCB4856 (see line 18 especially):
https://github.com/eyalbenda/bulkPop/blob/master/data-raw/createN2CB4856genome.R






--
-------------------------------------------------------------------------------------------------------------------------
Eyal Ben-David, PhD
Department of Biochemistry and Molecular Biology
The Institute for Medical Research Israel-Canada
The Hebrew University-Hadassah Medical School,
Ein Kerem, 91120, Jerusalem, Israel.
https://eyalbenda.github.io/

**Comment by JunKim-Worms** [comment]
Dear Professor Eyal Ben David,

Thank you so much for your comments! It's my honor to learn your skills.

Yours sinecerely,
Jun.
